---
- name: Install required packages
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - unzip

- name: Create wildfly user
  user:
    name: "{{wildfly_user}}"
    createhome: no
    shell: /bin/bash

- name: Download and extract tarball
  unarchive:
    src: "http://download.jboss.org/wildfly/{{wildfly_version}}/wildfly-{{wildfly_version}}.tar.gz"
    dest: "{{wildfly_basedir}}"
    creates: "{{wildfly_basedir}}/wildfly-{{wildfly_version}}"
    remote_src: yes
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"

- name: Make symbolic link to wildfly home
  file:
    src: "{{wildfly_basedir}}/wildfly-{{wildfly_version}}"
    dest: "{{wildfly_home}}"
    state: link
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"

- name: Make sure config dir exists
  file:
    path: /etc/wildfly
    state: directory
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"

- name: Copy confif file
  copy:
    src: wildfly.conf
    dest: /etc/wildfly/wildfly.conf
    mode: 0644

- name: Copy service script
  template:
    src: wildfly.service
    dest: /lib/systemd/system
    mode: 0644

- name: Link to systemd service
  file:
    src: /lib/systemd/system/wildfly.service
    dest: /etc/systemd/system/multi-user.target.wants/wildfly.service
    state: link
    mode: 0777

- name: Copy control script
  template:
    src: launch.sh
    dest: "{{wildfly_home}}/bin"
    owner: "{{wildfly_user}}"
    group: "{{wildfly_user}}"
    mode: 0777
  notify: Start wildfly service

